print string should be about txIn index, not txIn signature
ceyonur/bal pull request #4
Opened 2019-09-29 14:02 UTC by burakberk

'the txIn signature in coinbase tx must be the block height' : 'signature' should be 'index' since transaction['tx_ins'][0]['tx_out_index'] clearly refers to its index.

2019-09-29 20:35 UTC, ceyonur requested changes
please update your branch to latest master version, so we can solve the merge conflicts.

2019-09-30 08:47 UTC, burakberk commented
Branch updated to latest master version.

2019-10-09 08:08 UTC, ceyonur commented
:+1:

2019-10-09 08:08 UTC, ceyonur approved these changes

2019-10-09 08:08 UTC, merged